# Generated by Django 5.1.15 on 2026-06-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Visible on the public catalogue.'),
        ),
        migrations.AddField(
            model_name='historicalartefact',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Visible on the public catalogue.'),
        ),
    ]
