# Generated by Django 5.1.15 on 2026-10-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artefact",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="historicalartefact",
            name="uuid",
        ),
    ]
