# Generated by Django 5.1.15 on 2026-10-06 15:09

import core.uuids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_artefact_uuid_remove_historicalartefact_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetiredIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.uuids.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("object_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("merged", "Merged"), ("deleted", "Deleted")], max_length=10
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("former_title", models.CharField(blank=True, max_length=255)),
                ("retired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_identifiers",
                        to="catalog.artefact",
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-retired_at"],
            },
        ),
    ]
