# Generated by Django 5.1.15 on 2026-06-09 18:06

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50),
        ),
    ]
